apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: expenses-receipts
  namespace: expenses
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
