apiVersion: v1
kind: Secret
metadata:
    name: expenses-db-credentials
    namespace: expenses
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:PwI7XXEAiRw=,iv:Ag0gNep8OeK+w1ovyucLQeS/N0VyS9M4huIW8sSTPGQ=,tag:zbCv6cySyUowSoksiDsDOQ==,type:str]
    password: ENC[AES256_GCM,data:NiOfWveIgc02nlfX3mCKgJf25lnUcsT1iNk8ag==,iv:/DYbvreVVz2zUamE2cvq2woyPDuoBGdQyl3ChQwfcvU=,tag:e2WfgxqAE9W8BO/US70BSw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIRk1oUFRLYVFWYThzVVlv
            cU1FdEp1U0R2bC90YTQ4dDd4ZHNNZTVlNmdBCjFweTVJaFkvZVJaTk1HZG8yYk0z
            VnBTY2x3UUFaWE9TRW4vRFpqazNhdjQKLS0tIGN0QVBMZ2w0RTZrRWI0S29HQ3pD
            RDZDVU8zcVQ3emFlSEV4WTNUaDdoUU0KAY0k2EqiwMhiY5AXxfuPJ2qif9r67NU+
            nzO6dtkJ7W33d5rnDVINBDJ7gr1UYfF4jEr4nndDHu6tvst/h3H/CA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1erercrpsgf990dyfjuz430nt4vr7yrehegwn3pttww53ynm3pe0qqayz5j
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-31T13:09:05Z"
    mac: ENC[AES256_GCM,data:JRTdUKbJp/R4bnP5xN69y3lop+BlQ3yUfm+s/6vWLmVCLmK87heGRwzD3Gol/0BFoj07SKiP7vhc7DbNyIXwu9eRZZgLX27FDs5XBjKR8Chmaw8+vJ4eT/oEc1DYHAO1uCyB5Ekb3+QcMVv5zw8DZuN63Mry61lJJz27JcBiW64=,iv:7PDVbyHurUaASILFdHX6TiKs+VZsa5vpf2WDXgZGxl0=,tag:+M0WSE+psWTkclLZbp45vA==,type:str]
    version: 3.13.3
